/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/shoe-draco.glb -o ./src/demo/21/Model.tsx -t 
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import type React from "react";
import { type JSX, useEffect, useState } from "react";
import {
	Color,
	type ColorRepresentation,
	type Material,
	type Mesh,
	type MeshStandardMaterial,
} from "three";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";

type GLTFResult = GLTF & {
	nodes: {
		shoe: Mesh;
		shoe_1: Mesh;
		shoe_2: Mesh;
		shoe_3: Mesh;
		shoe_4: Mesh;
		shoe_5: Mesh;
		shoe_6: Mesh;
		shoe_7: Mesh;
	};
	materials: {
		laces: MeshStandardMaterial;
		mesh: MeshStandardMaterial;
		caps: MeshStandardMaterial;
		inner: MeshStandardMaterial;
		sole: MeshStandardMaterial;
		stripes: MeshStandardMaterial;
		band: MeshStandardMaterial;
		patch: MeshStandardMaterial;
	};
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
	const [hovered, setHovered] = useState(false);
	const { nodes, materials } = useGLTF(
		"/models/shoe-draco.glb",
	) as unknown as GLTFResult;

	useEffect(() => {
		document.body.style.cursor = hovered ? "pointer" : "auto";
	}, [hovered]);

	useControls("Shoe", () => {
		console.log("creating color pickers");
		return (Object.keys(materials) as (keyof typeof materials)[]).reduce(
			(acc, m) =>
				Object.assign(acc, {
					[m]: {
						value:
							"#" +
							((Math.random() * 0xffffff) << 0).toString(16).padStart(6, "0"),
						onChange: (v: ColorRepresentation) => {
							materials[m].color = new Color(v);
						},
					},
				}),
			{},
		);
	});

	return (
		<group
			{...props}
			dispose={null}
			onPointerOver={() => setHovered(true)}
			onPointerOut={() => setHovered(false)}
			onClick={(e) => {
				e.stopPropagation();
				document
					.getElementById(
						"Shoe." + ((e.object as unknown as Mesh).material as Material).name,
					)
					?.focus();
			}}
		>
			<mesh geometry={nodes.shoe.geometry} material={materials.laces} />
			<mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} />
			<mesh geometry={nodes.shoe_2.geometry} material={materials.caps} />
			<mesh geometry={nodes.shoe_3.geometry} material={materials.inner} />
			<mesh geometry={nodes.shoe_4.geometry} material={materials.sole} />
			<mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} />
			<mesh geometry={nodes.shoe_6.geometry} material={materials.band} />
			<mesh geometry={nodes.shoe_7.geometry} material={materials.patch} />
		</group>
	);
}

useGLTF.preload("/models/shoe-draco.glb");
