import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	webSidebar: [
		{
			type: "category",
			label: "Three",
			collapsed: true,
			items: [
				{
					type: "category",
					label: "基础",
					collapsed: true,
					items: [
						{
							type: "autogenerated",
							dirName: "web/three/basic",
						},
					],
				},
				{
					type: "category",
					label: "进阶",
					collapsed: true,
					items: [
						{
							type: "autogenerated",
							dirName: "web/three/advanced",
						},
					],
				},
				{
					type: "category",
					label: "综合",
					collapsed: true,
					items: [
						{
							type: "autogenerated",
							dirName: "web/three/showcases",
						},
					],
				},
			],
		},
		{
			type: "category",
			label: "Canvas",
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "web/canvas",
				},
			],
		},
		{
			type: "category",
			label: "Cesium",
			collapsed: true,
			items: [
				{
					type: "category",
					label: "基础",
					collapsed: true,
					items: [
						{
							type: "autogenerated",
							dirName: "web/cesium/basic",
						},
					],
				},
			],
		},
	],
};

export default sidebars;
